secret: 1@0@4*95*&JK987%$0

app:
  version: @project.version@

server:
  port: 8081

springdoc.api-docs.path: =/api-docs

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "moby:127.0.0.1"

feign:
  url:
    actionSaleSite: http://localhost:8080/v1/register-product
    brokerLoginSite: http://localhost:8081/v1/users

  compression:
    request:
      enabled: true
    response:
      enabled: true
    okhttp:
      enabled: true
    hystrix:
      enabled: false